---
# tasks file for certbot-cloudflare

- name: Get software for apt repository management.
  apt: name={{ item }} state=present
  with_items:
    - build-essential
    - curl
    - libffi-dev
    - libssl-dev
    - python3-apt
    - python3-dev
    - python3-pycurl
    - python3-certbot-dns-cloudflare

- name: Create certbot folder - sudouser
  file:
    path: /etc/letsencrypt
    state: directory
    owner: root
    group: root
    mode: 0700

- name: Certbot Template
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0600
  with_items:
    - { src: 'templates/confcloudflare.ini.j2', dest: '/etc/letsencrypt/dnscloudflare.ini' }
    - { src: 'templates/letsencrypt_cli.ini.j2', dest: '/etc/letsencrypt/cli.ini' }

- name: Create Certs.
  include_role:
    name: geerlingguy.certbot
